### DISCUSSION TITLE
Toolbar button background color always white

### DISCUSSION THREAD

**Discussion by MarcoFFSiciliano** [stephanrauh/ngx-extended-pdf-viewer#1949] [Q&A]
Hello,
i try to set the background color of the toolbar. The background color of the zoom dropdown and page number line-edit do not change / remain white. The 'normal' background changes correctly. 
Any ideas how to do this?

**Comment by stephanrauh** [comment]
You should be able to fix this by adding a CSS rule like this in the global `styles.(s)css` file:

```css
html ngx-extended-pdf-viewer .html .toolbarField,
html ngx-extended-pdf-viewer select {
   background-color: #fff !important;
}
```
