### ISSUE TITLE
Margin and Padding Broad CSS Rule

### ISSUE THREAD

**Issue by raygig** [stephanrauh/ngx-extended-pdf-viewer#1120]
Currently in viewer-with-images.scss there is some css that is removing all padding and margins from all child elements. I am creating a custom toolbar and this css rule is causing me to apply css overrides to deal with this very broad rule. A simple example is the padding in mat-rasied-buttons. 

Can you please remove this css rule?

```css
ngx-extended-pdf-viewer .html * {
    padding: 0;
    margin: 0;
}
```
