### ISSUE TITLE
Custom font for PDF and UI elements

### ISSUE THREAD

**Issue by muuvmuuv** [stephanrauh/ngx-extended-pdf-viewer#1423]
**Is your feature request related to a problem? Please describe.**

We already include many fonts and want to reduce the number of it. Would it therefor be possible to say `font-family: Inter var` so load this fond instead of the bundled version?

**Describe the solution you'd like**

Kinda like `font-family: Inter` or `[fontFamily]="'Inter'"`.

**Describe alternatives you've considered**

None

**Additional context**

/

**Comment by stephanrauh** [comment]
I suppose you can override the default fonts in the global.css file. You can find the font definition here: https://github.com/stephanrauh/ngx-extended-pdf-viewer/tree/main/projects/ngx-extended-pdf-viewer/src/lib/theme/common

Did you already try this?

**Comment by muuvmuuv** [comment]
Yes, found it! Thanks. I forgot that its just HTML and CSS haha

```css
  .body,
  .pdf-viewer input,
  .pdf-viewer button,
  .pdf-viewer select {
    font-family: var(--ion-font-family, inherit);
  }
```
