### ISSUE TITLE
Print Preview Content Allignment Issue

### ISSUE THREAD

**Issue by manzoorsharif123** [stephanrauh/ngx-extended-pdf-viewer#1446]
Hi,

Version ngx-extended-pdf-viewer - 8.2.0
![image](https://user-images.githubusercontent.com/108550245/177802297-e730d5d9-e6ba-45e1-878d-d249e81143ae.jpg)

While doing print preview and printing content is getting left allign and leaving space on right.

options tried :-
#printcontainer - css
embed - css 
both not working.

See attached screenshot.

Thanks & Regards,
Manzoor

**Comment by stephanrauh** [comment]
It seems you're already found the hot trace. It's almost certainly a CSS error.

**Comment by stephanrauh** [comment]
It's a far shot, but sometimes this CSS rule helps - especially if the print contains additional pages:

```css
body[data-pdfjsprinting] #printContainer>.printedPage {
  width: 99.99% !important; // or 99%
}
```
