### ISSUE TITLE
How to display single pages in book mode?

### ISSUE THREAD

**Issue by mariusbolik** [stephanrauh/ngx-extended-pdf-viewer#1565]
Hi Stephan,

I'm trying to build a mobile PDF viewer. I need to display only one page at the same time. `pageViewMode="book"` always shows 2 pages at the same time. When I use `[scrollMode]="1"`, there isn't this paging feeling.

What's the right way to only display one page at the same time and allow paging?

Regards,
Marius

**Comment by stephanrauh** [comment]
Sorry for answering late - I was a couple of days abroad. Can you explain me what a single-page book mode is? The only idea crossing my mind is a book consisting of pages that are only printed on one side. But still, when I turn a page, it has to go somewhere. To me, it's logical to display both piles of pages: the pages you've already read, and the pile of pages you're about to read. That's why my implementation of the book mode always displays two pages. Now I'm curious. Where are you heading to?

**Comment by mariusbolik** [comment]
Hi @stephanrauh,
thank you for taking the time!

I simply want to archive something like this:

<img src="https://user-images.githubusercontent.com/39862171/199481877-efafbf29-f324-4a5c-84d7-cdd0007dce11.gif" height="500px" />

It doesn't necessarily need to have the paging animation of a book, but it should stop on each page. This has a nicer usability on mobile devices than a fluently horizontal scroll.

It would be great if there is a simple and clean way to archive this. I tried with [CSS](https://css-tricks.com/css-only-carousel/) and [Swiper](https://swiperjs.com/) (which would be my preferred solution), but PDF Viewer doesn't load more than 3 pages using this approaches.

**Comment by mariusbolik** [comment]
The Video above is from the Books app from iPhone. Do you have a hint how I can archive this using your library?

**Comment by mariusbolik** [comment]
Got it, using only CSS. Thank you for the hints @stephanrauh!

```css
 #viewerContainer {
   scroll-snap-points-x: repeat(100vw);
   scroll-snap-type: x mandatory;
   scroll-snap-stop: always;
   scroll-behavior: smooth;
   scrollbar-color: transparent transparent;
   -webkit-overflow-scrolling: touch;

   .page {
     scroll-snap-align: start;
   }
 }
```
