### ISSUE TITLE
Changing color of Highlighted words of search results work locally but not in higher environment after deployment

### ISSUE THREAD

**Issue by Huey-H** [stephanrauh/ngx-extended-pdf-viewer#1578]
**Describe the bug**
Changes applied to styles are working in local but not working in higher environments. When inspecting the CSS on dev tools, the newly added color is not being picked up by the browser at all. Testing ::ng-deep with other components and they work fine but not with ngx-extended-pdf-viewer. Project uses SCSS.

**Version info**
- Version ^15.0.5

**Desktop (please complete the following information):**
 - Browser - Chrome
 
**Smartphone (please complete the following information):**
 - Device: N/A

**To Reproduce**
If you really can't provide me a reproducer, please tell me how to reproduce the behavior:
1. Go to component where ngx-extended-pdf-viewer is used.
2. Open imported SCSS file and include code snippet below:
```css
::ng-deep ngx-extended-pdf-viewer div.textLayer > span > .highlight.color0.selected {
  background: #ffda26 !important;
  border: 1px solid grey;
  opacity: 1;
}
```
4. Code above will work when project is served locally but does not work on deployed environment.
5. You'll see that the code above is nowhere to be found in dev tools on higher environment.

**Demo PDF file**
Searching within any PDF file.

**Thank you!**
Thank you for all your support in providing such an awesome package!
