### ISSUE TITLE
blank page

### ISSUE THREAD

**Issue by bpmsoftdev** [stephanrauh/ngx-extended-pdf-viewer#1587]
in my global styles.scss i've

```css
@media print {
    #printContainer > .printedPage {
        width: 99% !important;
    }
}
```

my component is
```html
    <ngx-extended-pdf-viewer *ngIf="file"
        [src]="file"
        [useBrowserLocale]="true"
        [textLayer]="true"
        [showHandToolButton]="true"
        [showPresentationModeButton]="true"
        [enablePrint]="true"
        [showPrintButton]="true"
                             [minifiedJSLibraries]="false"
        [showOpenFileButton]="false"
        [showRotateButton]="false"
        [showSecondaryToolbarButton]="false"
        [showBookmarkButton]="false"
        [showSidebarButton]="false"
        [showSpreadButton]="false"
        [showPropertiesButton]="false"
    >
    </ngx-extended-pdf-viewer>
```

but i view blank page on print preview

**Comment by stephanrauh** [comment]
Usually, there's an CSS rule interfering with printing. You've already found the 99% workaround, so I suppose you've already found and tried the hints I've given earlier. Nonetheless, I can't reproduce the bug, so all I can do is enabling you to hunt the bug yourself. I've collected  a short how-to here:

https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/1431#issuecomment-1162091452 

If you've found and solved the bug, please tell me, so I can close the ticket. If you need more help, don't hesitate to reach out to me.

**Comment by bpmsoftdev** [comment]
Hi stephanrauh, 
i've:
    - set the attribute [minifiedJSLibraries]="false"
    - open your PDF file in your app
    - open the developer tools (F12 or CMD+SHIFT+I on Mac)
    >>>> open the file viewer*.js in the source code tab

i can't found viewer.js in the souce tab

**Comment by stephanrauh** [comment]
You don't? Strange. Please try to find the file on my showcase (https://pdfviewer.net). You should be able to find the viewer-*.js over there, as my screenshot below shows. Once you know how and where to look, do the same with your project.

<img width="1727" alt="grafik" src="https://user-images.githubusercontent.com/3045767/203645098-411dc973-3830-4b4b-ac41-5ae5f33a9d35.png">

**Comment by bpmsoftdev** [comment]
![immagine](https://user-images.githubusercontent.com/98029542/204481189-4978e4d6-203e-43b0-a6af-e9097ef7f332.png)

**Comment by bpmsoftdev** [comment]
if I set visible the preview has white parts
![immagine](https://user-images.githubusercontent.com/98029542/204485339-6628ca1c-190f-4d15-932c-f4573e544d47.png)

**Comment by stephanrauh** [comment]
Where does `visibility: hidden`come from? Which version of the PDF viewer are you using? The relevant section of the current sourcecode uses `display: none`:
```scss
@media print {
  #printContainer {
    position: static;
    display: block;
  }

  body[data-pdfjsprinting],
  html {
    overflow-y: visible !important;
    margin: 0;
    padding: 0;
  }

  body[data-pdfjsprinting] {
    background: rgba(0, 0, 0, 0) none;
    height: 100%;
    width: 100%;

    & > * {
      display: none !important;
      outline: 0;
      padding: 0;
      margin: 0;
    }

    #printContainer {
      display: block !important;
      height: 100%;
      width: 100%;
    }

    #printContainer img {
      /* The intrinsic canvas / image size will make sure that we fit the page. */
      max-width: 100%;
      max-height: 100%;
      direction: ltr;
      display: block !important;
    }
```

**Comment by bpmsoftdev** [comment]
from layout-light.css line 2064

**Comment by stephanrauh** [comment]
Well, the current version of ngx-extended-pdf-viewer doesn't contain a file called `layout-light.css`. Maybe an older version did, but as far as I remember, I called the files differently. Is it a file you get from another source?

The current implementation of my CSS theming is a little non-standard. The rules are compiled into a TypeScript class (colors-css.ts). This class, in turn, has only a single line. This approach makes it easier to switch between different themes at runtime. The file `colors.scss` in the same source directory never makes it into the npm package. The build script compiles all the rules of `colors.scss` into the TypeScript file.

Here's the sourcecode: 
https://github.com/stephanrauh/ngx-extended-pdf-viewer/tree/main/projects/ngx-extended-pdf-viewer/src/lib/theme/pdf-light-theme

**Comment by stephanrauh** [comment]
I didn't hear from you for a long time. I'm closing the ticket now, hoping you've been able to solve the issue. If you're still stuck, don't hesitate to nudge me.

**Comment by tfactorygit** [comment]
As a clarification if  can help someone like me who broke his head for many hours .. i had the same issue and i think bpmsoftdev was using a PrimeNg template
The` layout-light.css` file derives from a child scss file` _invoice.scss` which contains a rule for managing the printing of a PrimeNg invoice template.  Find` src\assets\sass\layout\_invoice.scss` and turning` visibility: hidden;` to `visibility display; ` solve issue and print preview and print now is not empty

**Comment by chriskyndrid** [comment]
+1 for this, this continues to be an issue with primeNg:

```css
@media print {
  body * {
    visibility: hidden;
  }

  .layout-invoice-content {
    position: absolute;
    left: 0;
    top: 0;

    * {
      visibility: visible;
      box-shadow: none;
      color: #212121 !important;
      border-color: #e4e4e4 !important;
      background-color: transparent;
    }
  }
}

```

Is the default or similar for the _invoice.scss file.
