### ISSUE TITLE
customToolbar has style that messes with elements

### ISSUE THREAD

**Issue by jpike88** [stephanrauh/ngx-extended-pdf-viewer#1629]
https://github.com/stephanrauh/ngx-extended-pdf-viewer/blob/39de1fe3a90dbc1adc18b6f84e58a426cedbfdb6/projects/ngx-extended-pdf-viewer/src/lib/theme/common/viewer-with-images.scss#L188

The padding/margin styles here cause drama for whatever I decide to do in the toolbar area

**Comment by stephanrauh** [comment]
Quick workaround: you can always unset the rule:
```css
body ngx-extended-pdf-viewer .html .toolbar * {
    padding: unset;
    margin: unset;
}
```

The additional `body` selector hopefully is enough to override the selector Angular adds to the CSS rule. But maybe you need to add another selector to raise the priority.
