### ISSUE TITLE
Page number box height too large

### ISSUE THREAD

**Issue by Benaiah2320** [stephanrauh/ngx-extended-pdf-viewer#189]
I'm having trouble changing the height of the page number field in the toolbar. I'm guessing it's too large because of a schematic that I'm using that likely formats all inputs, including the one in the pdf viewer. I can find the css rule in the inspector, but trying to change it using the id (pageNumber) or classes (toolbarField and pageNumber) hasn't worked. I can see the source in the inspector and toggle it off there (it's under the input term), but can't find a way in through the css. 

You mentioned this issue in your documentation, but I'm not particularly skilled at css (thus the schematic) and I think it would be super helpful if you could give me some advice on how to do this, and then perhaps add it to your documentation for future users. 

Unfortunately I'm not really sure how to give you a minimum viable example, as I'm not sure where the issue is coming from and the schematic is internal to my company. 

Any help you can give would be great. Thanks!

**Comment by stephanrauh** [comment]
This (intentially exaggerated) code works in my test application:

```css
#pageNumber {
  font-size: 6px; /* reduze the font size */
  width: 20px;    /* make the input field smaller */
  height: 10px;   /* make the input field smaller */
  margin-top: 7px; /* push the input field down so it's nicely aligned with the larger texts */
  padding-left: 2px; /* reduce the size of the input field even more */
  padding-right: 2px; /* reduce the size of the input field even more */
}
```
![image](https://user-images.githubusercontent.com/3045767/71745513-a2be1a00-2e6a-11ea-9548-f657887cf4ea.png)

I'm pretty sure you're only interested in reducing the `font-size` attribute.  I've added the `height`, `width, `margin`, and `padding` attributes just in case. 

To my surprise, simply using the CSS class name doesn't work. Usually, I prefer this approach because CSS classes are more flexible than IDs, but it's overwritten by `toolbarField.pageNumber`:

![image](https://user-images.githubusercontent.com/3045767/71745825-971f2300-2e6b-11ea-8af2-e7c57cf28121.png)

```css
.pageNumber {  /* does not work! */
  font-size: 6px; /* reduze the font size */
  width: 20px;    /* make the input field smaller */
  height: 10px;   /* make the input field smaller */
  margin-top: 7px; /* push the input field down so it's nicely aligned with the larger texts */
  padding-left: 2px; /* reduce the size of the input field even more */
  padding-right: 2px; /* reduce the size of the input field even more */
}
```
![image](https://user-images.githubusercontent.com/3045767/71745805-866ead00-2e6b-11ea-97a3-754fc5da4494.png)

To solve this problem, you can add more specifc CSS selector. For example, adding both `.toolbar` and `input` works, at least in my demo:

```css
.toolbar input.pageNumber {
    font-size: 6px; /* reduze the font size */
    width: 20px;    /* make the input field smaller */
    height: 10px;   /* make the input field smaller */
    margin-top: 7px; /* push the input field down so it's nicely aligned with the larger texts */
    padding-left: 2px; /* reduce the size of the input field even more */
    padding-right: 2px; /* reduce the size of the input field even more */
}
```

If you still need help, don't hesitate to ask me. I know how much time it takes to get familiar with CSS. It's not difficult, but it's the same old story: at first, it looks like magic, until you spend a couple of days reading the documentation and playing around with it.

BTW: If my hints already help you, please tell me so I can close with issue.

Best regards,
Stephan

**Comment by Benaiah2320** [comment]
Stephan, 

Thanks for the quick reply. I spent some time last week and this morning looking at it, but I couldn't get it to change with any of the examples you gave, or some other combinations. I dug a little deeper into CSS selectors to try to be able to find this one (classes, id, etc), but nothing I did seemed to make a difference. Here's a little bit more about the problem:
![pdf-input](https://user-images.githubusercontent.com/32401880/71825437-dca93f00-3069-11ea-933f-f6432b6ce3d4.png)
Both of these are input classes, and the schematic I'm using seems to be setting both of them to a height of 48px. 
I can find this in the inspector tool:
![pdf-input2](https://user-images.githubusercontent.com/32401880/71825485-fd719480-3069-11ea-865a-b1116dafb1d5.png)
and toggling it off makes the page number input look correct:
![pdf-input3](https://user-images.githubusercontent.com/32401880/71825528-11b59180-306a-11ea-9aca-47a083270662.png)
I just can't seem to access it. I'm beginning to think that it may have something to do with the way angular applies the CSS rules on build? I'm not very familiar with this stuff, I spend more time on the backend. 

Either way I don't think it has something to do with ngx-extended-pdf-viewer (which is great btw, thanks!), so unless you have some last bits of advice I don't want to take up your time. Thanks for your help already!

**Comment by stephanrauh** [comment]
You've inspired me to write an article about CSS. I'd recommend reading it, but I believe you already know everything I've written. :) I'll give you the links nonetheless, just in case (and I'd appreciate for feedback, no matter if it's good or bad): https://beyondjava.net/gentle-introduction-css

Enough self-advertising. :) By the way, thanks for the kind words. It feels great to know my little work makes your life easier!

**Comment by stephanrauh** [comment]
Back to topic. Maybe you can send me a copy of the entire CSS tab. As far as I can see, the `height` is the culprit, so you can filter the rule set:

![image](https://user-images.githubusercontent.com/3045767/71844256-10b24d80-30c6-11ea-97bb-99b33dc0117c.png)

**Comment by stephanrauh** [comment]
Taking the screenshot, I saw there's no rule concerning the height of input fields in the PDF viewer. So let's take a different route. Your `height` rule is defined at line 11967 of your HTML file. If you're using Google Chrome, you can click the link (the gray text `inline: 11967`). Now you see the offending CSS rule, plus a bit of context. Often that's enough to guess what's causing the problem. My guess: there's a rule with an `!important` qualifier, so your attempts to override it are doomed to fail.

**Comment by stephanrauh** [comment]
One last idea: start your application with `ng s -o --optimization=false`. That disables CSS minification. So it's easier to recognize the source code causing the problem.

If that still doesn't help, I often copy the non-minified code and start a global search. The idea being that it's easy to override the offending rule once you know what it looks like.

**Comment by Benaiah2320** [comment]
Your article was great!  I felt a little targeted haha, but it was just what I needed. Too many of them are just a crash course in CSS that's too deep and not usable. That was a good introduction for someone like me who just wants to make some changes to a template.

I traced it using the inline link you mentioned, and it went through a couple scss files. From what I can tell scss is a superset of css like what typescript is to javascript, so raw css should still work? Either way here's the trail:
```
input {
  @include make-form-input;
}
```
to 
```
@mixin make-form-input {
  color: $font-color;
  height: $form-field-size-base;
  padding: 0 $gridSize;
  background-size: 100% 200%;
  background-image: linear-gradient(to top, $companyLightGray25 50%, $companyLightGray15 50%);
  box-shadow: none;
  transition: .2s;
  line-height: $form-field-size-base / 2 + 2;

  @include make-font;
  @include make-border(0px 0px 1px 0px, $companyLightGray75);
  @include make-form-control-states;
  @include placeholder($companyDarkGray25);
}
```
(I replaced my company name with `company`, not sure if I'm allowed to expose it, but whatever)
and then to
```
//== Formfield size
$form-field-size-base: $gridSize * 6;
```
and finally to
```
// Base Value for the Grid size
$gridSize:                8px;
```
It doesn't look like there is an `!important` tag overriding anything, but I still can't get it to change, no matter what selection I use.

At least this points to a likely issue with the schematic and not the pdf viewer, so I can more confidently go to our internal support with this as something that definitely involves their schematic.

Thanks again for all of your help!

**Comment by stephanrauh** [comment]
Thanks for the kind words again! I tried hard to avoid that "feeling targeted" bit, but I guess that's one of the things that are almost impossible. Especially in a foreign language. I guess I can express myself well enough in English, but without doubt, there are nuances I'll always miss. So I'm happy you like the article. I'm always glad to help!

**Comment by stephanrauh** [comment]
Comparing SCSS to TypeScript is a good metaphor. It add stuff like nested selectors, variables, mixins, inheritance and so on. It's great, but when I can use Angular, I hardly ever use SCSS. The local CSS approach of Angular does the trick just as well for me.

I'm still confused. Your SCSS snippet doesn't look that exotic. I guess it simply compiles to 
```CSS
input { 
  height: 48px; 
}
```
Maybe the problem is just the load order. Are you sure your CSS rule is loaded after the SCSS stylesheet?

**Comment by Benaiah2320** [comment]
Feeling targeted wasn't bad, just funny to have an article so directly related to what I'm trying to do. Usually you have to read through a bunch of stuff that doesn't matter. It's impressive for English not being your second language though.

**Comment by Benaiah2320** [comment]
I don't know when the schematic stylesheet is being loaded. I'm editing the scss sheet for the component, so it would be whenever that's loaded. I mentioned the scss because I thought maybe the way it compiles the css could be overwriting my changes with the schematic's styles.

**Comment by stephanrauh** [comment]
I see. That sounds like you're using a framework like Liferay, Confluence or Wordpress. Well, your stylesheet can be loaded at any moment. I suppose you can see that in the HTML page, but more likely than not, it's loaded early. Most people prefer to put their CSS into the header of the HTML page.

However, you can add your CSS rules anywhere. What does your project look like - is it an Angular CLI project?  If so, you can add your CSS rule to the `index.html`. 

```css
  </head>

  <body>
    <app-root></app-root>
    <style>
      .toolbar input.pageNumber {
        background-color: red;
        font-size: 6px; /* reduze the font size */
        width: 20px;    /* make the input field smaller */
        height: 10px;   /* make the input field smaller */
        margin-top: 7px; /* push the input field down so it's nicely aligned with the larger texts */
        padding-left: 2px; /* reduce the size of the input field even more */
        padding-right: 2px; /* reduce the size of the input field even more */
    }
    </style>
  </body>
</html>
```

![image](https://user-images.githubusercontent.com/3045767/72016667-85bb8980-3264-11ea-94e9-bb612de4701d.png)
