### ISSUE TITLE
TextLayer markings added programmatically are not visibile

### ISSUE THREAD

**Issue by Hely0n** [stephanrauh/ngx-extended-pdf-viewer#1934]
TextLayer markings are not visibile. I tried every code snipped from https://pdfviewer.net/extended-pdf-viewer/textlayer but nothing helps. I noticed, that I have to use "event.source.textlayer?.textDivs..." and the loop is indeed executing, but nothing is visible. What am I doing wrong? Here is my Code (now more concise than the code in the demo, to keep it short):

CSS:

```css
.highlighted { // just added some things to see something
  border: solid 1px #000000;
  background-color: #000000;
}
```

TS:
```ts
public highlightWords(event: TextLayerRenderedEvent): void {
    //just mark everything
    event.source.textLayer?.textDivs.forEach((span) => {
      span.classList.add('highlighted');
    });
}
```

HTML:
```html
<div class="flex-fill">
    <ngx-extended-pdf-viewer
      [src]="this.pdfSrc!"
      [height]="'auto'"
      [zoom]="'page-width'"
      [textLayer]="true"
      [handTool]="false"
      (textLayerRendered)="highlightWords($event)">
    </ngx-extended-pdf-viewer>
 </div>
```
  
  
Version: 18.1.4
The pdf viewer itself is working fine, even the find bar works and is marking the found text.
