### ISSUE TITLE
css conflict @angular/material / tailwind

### ISSUE THREAD

**Issue by fiedler-itlabs** [stephanrauh/ngx-extended-pdf-viewer#2291]
There seems to be a css conflict with ngx-extended-pdf-viewer and @angular/material and/or tailwind. The conflict shows in the toolbar:

![image](https://github.com/stephanrauh/ngx-extended-pdf-viewer/assets/94529792/58fa6f69-d518-4ef0-a1f1-d81f9194fcd7)

The conflict is not present in the version 18.1.14

dependencies:
"@angular/material": "17.3.3",
"tailwindcss": "3.4.3",
"ngx-extended-pdf-viewer": "19.7.1"

I worked around the conflict by hiding the spans in my component:
```css
styles: `
  .toolbarButton > span {
    display: none !important;
  }
`,
```
