### ISSUE TITLE
Annotation can not be dragged to next page

### ISSUE THREAD

**Issue by AdrianM** [stephanrauh/ngx-extended-pdf-viewer#2518]
An annotation can not be dragged to the next page (but to the previous, it works).

**Reproduce the bug**
1. Open the showcase https://pdfviewer.net/extended-pdf-viewer/simple
2. Scroll down to page 2
3. Click in the toolbar on 'add or edit image' => 'Add image' => add an svg image (e.g. https://mozilla.github.io/pdf.js/images/logo.svg)
4. Move image to page 3 => bug: is gets stuck at the buttom of page 2. (Hint: moving the image to page 1 works perfectly fine)

Hint: in the PDS.js showcase, it looks like it works https://mozilla.github.io/pdf.js/web/viewer.html.

**Version info**
- Version 21.3.2, tested on Chrome 127.0 on a MacOS 14.6.1. We add annotations with `pdfServiceInstance.addImageToAnnotationLayer(...)` in our project, the behaviour is the same.

**Comment by stephanrauh** [comment]
Every annotation is affected, not only the stamps. But I'm afraid it will be difficult to find the cause. Unless a weird mistake happened, the source code should be identical to the pdf.js sourcecode. Could it be a CSS problem?

**Comment by stephanrauh** [comment]
I really seems to be a CSS issue. I've observed two differences to Mozilla's showcase:

The z-index rule is missing:
```css 
.annotationEditorLayer .selectedEditor {
    z-index: 100000 !important;
}
```

The `.page` div has a different overflow setting. It should be
```css
pdfViewer .page {
    direction: ltr;
    width: 816px;
    height: 1056px;
    margin: var(--page-margin);
    position: relative;
    overflow: visible;
    overflow-x: visible;
    overflow-y: visible;
    border: var(--page-border);
    background-clip: content-box;
    background-color: rgb(255 255 255);
```
but it is
```css
ngx-extended-pdf-viewer .pdfViewer .page {
    direction: ltr;
    width: 816px;
    height: 1056px;
    margin: 1px auto -8px;
    position: relative;
    overflow: hidden;
    overflow-x: hidden;
    overflow-y: hidden;
    border: 9px solid rgba(0, 0, 0, 0);
    background-clip: content-box;
    -o-border-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABMAAAATCAQAAADYWf5HAAAA6UlEQVR4Xl2Pi2rEMAwE16fm1f7/r14v7w4rI0IzLAF7hLxNevBSEMEF5+OilNCsRd8ZMyn+a4NmsOT8WJw1lFbSYgGFzF2bLFoLjTClWjKKGRWpDYAGXUnZ4uhbBUzF3Oe/GG/ue2fn4GgsyXhNgysV2JnrhKEMg4fEZcALmiKbNhBBRFpSyDOj1G4QOVly6O1FV54ZZq8OVygrciDt6JazRgi1ljTPH0gbrPmHPXAbCiDd4GawIjip1TPh9tt2sz24qaCjr/jAb/GBFTbq9KZ7Ke/Cqt8nayUikZKsWZK7Fe6bg5dOUt8fZHWG2BHc+6EAAAAASUVORK5CYII=) 9 9 repeat;
    border-image: url(data:image/png;base64,...) 9 9 repeat;
    background-color: #fff;
    filter: opacity(1);
    -webkit-filter: opacity(1);
}
```
