### ISSUE TITLE
The Last Page Is Printing Blank

### ISSUE THREAD

**Issue by jayeshsony** [stephanrauh/ngx-extended-pdf-viewer#2678]
I encountered an issue where a blank page was being printed before each page. To fix this, I applied the following CSS code:

```css
@media print {
  #printContainer > .printedPage {
    width: 99% !important;
    margin-top: -65px !important;
  }
}
```

This solution works on most browsers, but in Chrome, the last page of the report is printing as a blank page. This issue only happens in Chrome, except for version 129.0, where it works fine.
