### ISSUE TITLE
Responsive-CSS-override hack is broken

### ISSUE THREAD

**Issue by stephanrauh** [stephanrauh/ngx-extended-pdf-viewer#355]
@prasanthnsn11 reports in #112 that the download button remains invisible on small devices, even if you try to override the default CSS that hides it.

Currently, the feature can be seen at https://pdfviewer.net/smartphone. The buttons are there and they even work, but you can't see them because there's no image. Just a tiny hover effect when moving the mouse over the button.

**Comment by stephanrauh** [comment]
As it turns out, the CSS rules must be changed a bit to accommodate the new Material Design layout:

```CSS
/* /deep/ is deprecated, so move this to the global styles.css if possible! */
/deep/ button#print,
/deep/ button#print * { /* new! */
  display: block !important;
}

/deep/ button#download,
/deep/ button#download * { /* new! */
  display: block !important;
}
```
