### ISSUE TITLE
Wrong position of the PDF

### ISSUE THREAD

**Issue by lucho78** [stephanrauh/ngx-extended-pdf-viewer#747]
Hello,
I guess I found an issue in the latest version.
The top value on the element "viewerContainer" is wrong. The concequences are the preview is not displayed from the top.
![image](https://user-images.githubusercontent.com/14161954/117405070-545fd600-af0b-11eb-9186-3dd1364808ba.png)

![image](https://user-images.githubusercontent.com/14161954/117405143-693c6980-af0b-11eb-9f3f-69c7a431c429.png)

To solve this issue I added in my code:
```css
ngx-extended-pdf-viewer #viewerContainer {
    top: 35px !important;
}
```

Maybe it could be nice to solve it in the component itself.
Thanks
Luc
