### ISSUE TITLE
Use position: absolute in the print CSS

### ISSUE THREAD

**Issue by stephanrauh** [stephanrauh/ngx-extended-pdf-viewer#954]
@rekna1 suggests in #152 to add this CSS rule to the print CSS:

```css
@media print {
  #printContainer { position: absolute; }
}
```

They report that the default setting shows only one page in the print preview. Let's investigate if it's safe to replace the default (`position: static`) by `position: absolute`.
